#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

mkdir -p content src/data src/rag src/chat src/sections src/effects \
         scripts/lib tests api generated .github/workflows qa-lab/tests public docs

cat > package.json <<'JSON'
{
  "name": "vincent-liu-qa-portfolio",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "dev:api": "vercel dev",
    "parse:content": "tsx scripts/parse-content.ts",
    "rag:build": "tsx scripts/build-rag-index.ts",
    "rag:test": "tsx scripts/rag-test.ts",
    "build": "pnpm parse:content && vite build",
    "preview": "vite preview",
    "test": "vitest run",
    "test:e2e": "playwright test",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": { "three": "^0.169.0" },
  "devDependencies": {
    "@playwright/test": "^1.48.0",
    "@types/node": "^22.7.0",
    "@types/three": "^0.169.0",
    "tsx": "^4.19.0",
    "typescript": "^5.6.0",
    "vercel": "^37.0.0",
    "vite": "^5.4.0",
    "vitest": "^2.1.0"
  }
}
JSON

cat > tsconfig.json <<'JSON'
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "strict": true,
    "noUncheckedIndexedAccess": true,
    "noEmit": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "verbatimModuleSyntax": true,
    "types": ["node", "vitest/globals"]
  },
  "include": ["src", "scripts", "tests", "api", "vite.config.ts"]
}
JSON

cat > vite.config.ts <<'TS'
import { defineConfig } from 'vite';
export default defineConfig({
  base: './',
  build: { outDir: 'dist', assetsDir: 'assets', sourcemap: false },
  server: { port: 5173 },
});
TS

cat > vercel.json <<'JSON'
{ "functions": { "api/chat.ts": { "runtime": "edge" } } }
JSON

cat > .env.example <<'ENV'
OPENAI_API_KEY=sk-...
OPENAI_EMBEDDING_MODEL=text-embedding-3-small
OPENAI_ANSWER_MODEL=gpt-5-mini
ALLOWED_ORIGINS=https://your-user.github.io,http://localhost:5173
VITE_API_URL=
ENV

cat > .gitignore <<'GIT'
node_modules/
dist/
.env
.vercel
*.log
.DS_Store
qa-lab/playwright-report/
qa-lab/test-results/
GIT

cat > src/data/schema.ts <<'TS'
export type ChunkType =
  | 'summary' | 'experience' | 'project' | 'skill' | 'capability' | 'ai-practice';

export interface Identity { name: string; role: string; direction: string; }
export interface SubProject {
  id: string; name: string;
  responsibilities: string[]; technology: string[]; themes: string[];
}
export interface Experience {
  id: string; company: string; role: string; period: string;
  subProjects: SubProject[];
}
export interface AcademicProject {
  id: string; name: string; institution: string; year: number;
  overview: string; technology: string[]; development: string[]; concepts: string[];
}
export interface SkillGroup { id: string; category: string; items: string[]; }
export interface Flow { id: string; name: string; steps: string[]; context?: string; }
export interface AiPractice {
  id: string; name: string; description: string; bullets: string[];
  tools: string[]; usage: string[]; workflowSteps: string[];
}
export interface Profile {
  identity: Identity; positioning: string; narrative: Flow;
  experience: Experience[]; academicProjects: AcademicProject[];
  skills: SkillGroup[]; capabilities: Flow[]; aiPractices: AiPractice[];
}
TS

cat > src/data/profile.ts <<'TS'
// AUTO-GENERATED by scripts/parse-content.ts
export const profile = null as never;
TS

cat > src/vite-env.d.ts <<'TS'
/// <reference types="vite/client" />
interface ImportMetaEnv { readonly VITE_API_URL?: string; }
interface ImportMeta { readonly env: ImportMetaEnv; }
TS

cat > src/main.ts <<'TS'
import { profile } from './data/profile.ts';
import { initGhostCursor } from './effects/ghost-cursor.ts';
import { initParticleHeading } from './effects/particle-heading.ts';
import { initScrollAnimations } from './effects/scroll-animations.ts';
import { initCardGlow } from './effects/card-glow.ts';
import { initFlowAnimations } from './effects/flow-animations.ts';
import { initNavSpy } from './effects/nav-spy.ts';
import { initCharacterFollow } from './effects/character-follow.ts';
import { renderHighlights } from './sections/highlights.ts';
import { renderAbout } from './sections/about.ts';
import { renderCapabilities } from './sections/capabilities.ts';
import { renderExperience } from './sections/experience.ts';
import { renderProjects } from './sections/projects.ts';
import { initChat } from './chat/client.ts';

function boot(): void {
  renderHighlights(profile);
  renderAbout(profile);
  renderCapabilities(profile);
  renderExperience(profile);
  renderProjects(profile);
  initGhostCursor();
  initParticleHeading();
  initCardGlow();
  initFlowAnimations();
  initScrollAnimations();
  initNavSpy();
  initCharacterFollow();
  initChat();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', boot);
} else {
  boot();
}
TS

cat > src/sections/highlights.ts <<'TS'
import type { Profile } from '../data/schema.ts';

export function renderHighlights(_profile: Profile): void {
  const container = document.getElementById('highlight-grid');
  if (!container) return;
  const cards = [
    { title: 'Automation Engineering',
      body: 'Reusable JavaScript and Playwright automation for web, API, and end-to-end workflows. Page Objects, business components, shared utilities.' },
    { title: 'API & Integration',
      body: 'REST API validation with Postman and Swagger. Connected-system testing, authentication validation, downstream-service investigation.' },
    { title: 'Debugging & Root Cause',
      body: 'Tracing failures across logs, API responses, SQL data, and application behaviour to identify root causes and verify fixes.' },
  ];
  container.innerHTML = cards.map((c) => `
    <article class="highlight-card">
      <h3>${c.title}</h3>
      <p>${c.body}</p>
    </article>`).join('');
}
TS

cat > src/sections/about.ts <<'TS'
import type { Profile } from '../data/schema.ts';

export function renderAbout(profile: Profile): void {
  const copy = document.getElementById('positioning-copy');
  if (copy) copy.textContent = profile.positioning;
  const grid = document.getElementById('skill-grid');
  if (!grid) return;
  grid.innerHTML = profile.skills.map((s) => `
    <article class="skill-card" data-profile-id="${s.id}">
      <h3>${s.category}</h3>
      <ul>${s.items.map((i) => `<li>${i}</li>`).join('')}</ul>
    </article>`).join('');
}
TS

cat > src/sections/capabilities.ts <<'TS'
import type { Profile } from '../data/schema.ts';

export function renderCapabilities(profile: Profile): void {
  const grid = document.getElementById('flow-grid');
  if (!grid) return;
  grid.innerHTML = profile.capabilities.map((flow) => `
    <article class="flow-card" data-profile-id="${flow.id}">
      <h3>${flow.name}</h3>
      <div class="flow-steps" data-flow-id="${flow.id}">
        ${flow.steps.map((step, i) =>
          `<div class="flow-step" style="--step-index: ${i}">${step}</div>`).join('')}
      </div>
    </article>`).join('');
}
TS

cat > src/sections/experience.ts <<'TS'
import type { Profile } from '../data/schema.ts';

export function renderExperience(profile: Profile): void {
  const list = document.getElementById('experience-list');
  if (!list) return;
  list.innerHTML = profile.experience.map((exp) => `
    <article class="experience-item" data-profile-id="${exp.id}">
      <span class="period">${exp.period}</span>
      <h3>${exp.company}</h3>
      <p class="role">${exp.role}</p>
      ${exp.subProjects.map((sub) => `
        <div class="subproject" data-profile-id="${sub.id}">
          <h4>${sub.name}</h4>
          <ul>${sub.responsibilities.map((r) => `<li>${r}</li>`).join('')}</ul>
          <div class="tech-tags">
            ${sub.technology.map((t) => `<span class="tech-tag">${t}</span>`).join('')}
          </div>
        </div>`).join('')}
    </article>`).join('');
}
TS

cat > src/sections/projects.ts <<'TS'
import type { Profile } from '../data/schema.ts';

export function renderProjects(profile: Profile): void {
  const stack = document.getElementById('project-stack');
  if (!stack) return;
  stack.innerHTML = profile.academicProjects.map((p) => `
    <article class="project-card" data-profile-id="${p.id}">
      <span class="year">${p.year} · ${p.institution}</span>
      <h3>${p.name}</h3>
      <p>${p.overview}</p>
    </article>`).join('');
}
TS

cat > src/effects/card-glow.ts <<'TS'
export function initCardGlow(): void {
  const cards = document.querySelectorAll<HTMLElement>('.skill-card');
  for (const card of cards) {
    card.addEventListener('pointermove', (e) => {
      const rect = card.getBoundingClientRect();
      const x = ((e.clientX - rect.left) / rect.width) * 100;
      const y = ((e.clientY - rect.top) / rect.height) * 100;
      card.style.setProperty('--glow-x', `${x}%`);
      card.style.setProperty('--glow-y', `${y}%`);
    });
  }
}
TS

cat > src/effects/scroll-animations.ts <<'TS'
export function initScrollAnimations(): void {
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (reduced) {
    document.querySelectorAll<HTMLElement>('.highlight-card, .skill-card').forEach((el) => {
      el.classList.add('is-visible');
    });
    return;
  }
  let lastScrollY = window.scrollY;
  let direction: 'down' | 'up' = 'down';
  window.addEventListener('scroll', () => {
    direction = window.scrollY > lastScrollY ? 'down' : 'up';
    lastScrollY = window.scrollY;
  }, { passive: true });
  const observer = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      const el = entry.target as HTMLElement;
      if (entry.isIntersecting && direction === 'down') el.classList.add('is-visible');
      else if (!entry.isIntersecting && direction === 'up') el.classList.remove('is-visible');
    }
  }, { threshold: 0.18 });
  document.querySelectorAll<HTMLElement>('.highlight-card, .skill-card')
    .forEach((el) => observer.observe(el));
}
TS

cat > src/effects/flow-animations.ts <<'TS'
export function initFlowAnimations(): void {
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const observer = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      if (!entry.isIntersecting) continue;
      const container = entry.target as HTMLElement;
      const steps = container.querySelectorAll<HTMLElement>('.flow-step');
      if (reduced) { steps.forEach((s) => s.classList.add('is-active')); continue; }
      steps.forEach((step, i) => setTimeout(() => step.classList.add('is-active'), i * 180));
      observer.unobserve(container);
    }
  }, { threshold: 0.3 });
  document.querySelectorAll<HTMLElement>('.flow-steps').forEach((el) => observer.observe(el));
}
TS

cat > src/effects/nav-spy.ts <<'TS'
const TRIGGER_ROOT_MARGIN = '-25% 0px -65% 0px';

export function initNavSpy(): void {
  const links = Array.from(document.querySelectorAll<HTMLAnchorElement>('.nav-link'));
  if (links.length === 0) return;
  const linkById = new Map<string, HTMLAnchorElement>();
  for (const link of links) {
    const href = link.getAttribute('href');
    if (!href?.startsWith('#')) continue;
    linkById.set(href.slice(1), link);
  }
  const sections = Array.from(linkById.keys())
    .map((id) => document.getElementById(id))
    .filter((el): el is HTMLElement => el !== null);
  if (sections.length === 0) return;

  function setActive(id: string): void {
    for (const [sectionId, link] of linkById) {
      link.classList.toggle('is-active', sectionId === id);
    }
  }

  const observer = new IntersectionObserver((entries) => {
    const intersecting = entries
      .filter((e) => e.isIntersecting)
      .sort((a, b) => a.boundingClientRect.top - b.boundingClientRect.top);
    const top = intersecting[0];
    if (top) setActive(top.target.id);
  }, { rootMargin: TRIGGER_ROOT_MARGIN, threshold: 0 });

  for (const section of sections) observer.observe(section);
}
TS

cat > src/effects/character-follow.ts <<'TS'
const MAX_TILT = 6;
const MAX_SHIFT_X = 18;
const MAX_SHIFT_Y = 8;
const EASE = 0.12;

export function initCharacterFollow(): void {
  const char = document.getElementById('character');
  if (!char) return;
  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;
  let raf: number | null = null;
  let targetX = 0, targetY = 0;
  let currentX = 0, currentY = 0;
  const clamp = (v: number, min: number, max: number) => v < min ? min : v > max ? max : v;

  function onMove(e: PointerEvent): void {
    const cx = window.innerWidth / 2;
    const cy = window.innerHeight / 2;
    targetX = clamp((e.clientX - cx) / cx, -1, 1);
    targetY = clamp((e.clientY - cy) / cy, -1, 1);
    if (!raf) raf = requestAnimationFrame(tick);
  }

  function tick(): void {
    currentX += (targetX - currentX) * EASE;
    currentY += (targetY - currentY) * EASE;
    char!.style.setProperty('--tilt', (currentX * MAX_TILT).toFixed(2) + 'deg');
    char!.style.setProperty('--shift-x', (currentX * MAX_SHIFT_X).toFixed(2) + 'px');
    char!.style.setProperty('--shift-y', (currentY * MAX_SHIFT_Y).toFixed(2) + 'px');
    if (Math.abs(targetX - currentX) > 0.001 || Math.abs(targetY - currentY) > 0.001) {
      raf = requestAnimationFrame(tick);
    } else raf = null;
  }

  window.addEventListener('pointermove', onMove, { passive: true });
  window.addEventListener('pointerleave', () => {
    targetX = 0; targetY = 0;
    if (!raf) raf = requestAnimationFrame(tick);
  });
}
TS

echo "✓ A-base done"
ls -la