// AUTO-GENERATED by scripts/parse-content.ts
// DO NOT EDIT MANUALLY.
import type { Profile } from './schema.ts';
export const profile: Profile = {
  "identity": {
    "name": "Vincent Liu",
    "role": "QA Engineer / QA Automation Engineer",
    "direction": "Quality Engineering, Software Engineering, and AI Engineering."
  },
  "positioning": "Vincent is a QA Engineer with experience across web applications, APIs, end-to-end business workflows, backend data validation, system integrations, and test automation.\n\nHis experience combines software quality with hands-on engineering practices, including JavaScript/Playwright automation, reusable test architecture, REST API testing, SQL-based data validation, CI/CD integration, debugging, and AI-assisted development.\n\nThe portfolio should present him as more than a manual tester. The core engineering story is:\n\n**Understand the system → build reusable automation → investigate failures → trace data and integrations → validate behaviour → improve quality.**\n\n---",
  "experience": [
    {
      "id": "exp-p97",
      "company": "P97",
      "role": "QA Engineer",
      "period": "2023–2026",
      "subProjects": [
        {
          "id": "exp-p97-fleet-platform",
          "name": "Fleet Platform",
          "responsibilities": [
            "Developed and maintained reusable JavaScript and Playwright automation for web, API, and end-to-end workflows.",
            "Built reusable Page Objects, business components, and shared utilities to improve code reuse and maintainability.",
            "Worked with REST APIs using Postman and Swagger to validate requests, responses, JSON data, authentication, and system integrations.",
            "Used SQL to validate backend data and trace data flow across applications, APIs, and connected systems.",
            "Integrated automated tests into Azure DevOps CI/CD pipelines for pull request validation, scheduled testing, and release verification.",
            "Used Mockoon to simulate dependent APIs and test integration workflows when external services were unavailable.",
            "Investigated application and automation failures using logs, API responses, test traces, and SQL data to identify root causes and verify fixes.",
            "Used Claude and GitHub Copilot to generate, debug, and improve JavaScript automation code and documentation. Reviewed and validated AI-generated outputs before implementation.",
            "Tested AI-powered features and validated AI-generated results against expected business rules and application behaviour.",
            "Wrote BDD scenarios using Gherkin and implemented step definitions with Cucumber-JS and Playwright.",
            "Worked with developers, Product Owners, and Business Analysts to turn requirements into test scenarios and technical solutions."
          ],
          "technology": [
            "JavaScript",
            "Playwright",
            "Cucumber-JS",
            "Gherkin",
            "REST APIs",
            "Postman",
            "Swagger",
            "SQL",
            "Mockoon",
            "Azure DevOps",
            "CI/CD",
            "Claude",
            "GitHub Copilot"
          ],
          "themes": [
            "Reusable Automation",
            "API & Integration",
            "Data Validation",
            "CI/CD",
            "Root-Cause Investigation",
            "AI-Assisted Development",
            "BDD",
            "E2E Testing"
          ]
        },
        {
          "id": "exp-p97-mem-platform",
          "name": "MEM Platform",
          "responsibilities": [
            "Built and maintained reusable Playwright Page Objects for application workflows.",
            "Refactored duplicated automation logic into reusable components.",
            "Validated data flow between frontend applications, APIs, and downstream services.",
            "Used SQL and API responses to investigate integration issues and data inconsistencies.",
            "Used Claude to support JavaScript development, automation improvements, and debugging."
          ],
          "technology": [],
          "themes": [
            "Playwright",
            "Page Object Model",
            "Reusable Components",
            "Frontend/API Integration",
            "SQL",
            "Data Investigation",
            "JavaScript",
            "AI-Assisted Development"
          ]
        }
      ]
    },
    {
      "id": "exp-kevorld",
      "company": "Kevorld",
      "role": "QA Engineer",
      "period": "2021–2023",
      "subProjects": [
        {
          "id": "exp-kevorld-general",
          "name": "General",
          "responsibilities": [
            "Developed and maintained Playwright automation for insurance quoting and policy workflows.",
            "Worked with Salesforce, REST APIs, and SQL to validate data and integrations across connected systems.",
            "Used Postman to test API requests, responses, and business workflows.",
            "Investigated application issues by tracing data across the frontend, Salesforce, and APIs.",
            "Worked with developers to identify root causes and verify fixes."
          ],
          "technology": [
            "Playwright",
            "Salesforce",
            "REST APIs",
            "Postman",
            "SQL"
          ],
          "themes": [
            "Insurance Workflows",
            "System Integration",
            "API Validation",
            "Data Tracing",
            "Application Debugging"
          ]
        }
      ]
    }
  ],
  "academicProjects": [
    {
      "id": "proj-simulated-taxi-booking-web-application",
      "name": "Simulated Taxi Booking Web Application",
      "institution": "Auckland University of Technology (AUT)",
      "year": 2022,
      "overview": "A simulated full-stack taxi booking web application developed as an academic software project.",
      "technology": [
        "Java",
        "MySQL",
        "HTML",
        "CSS",
        "HTTP",
        "JSON",
        "Git",
        "Agile"
      ],
      "development": [
        "Developed a full-stack taxi booking application using Java, MySQL, HTML, and CSS.",
        "Implemented frontend-to-backend communication using HTTP requests and JSON.",
        "Developed CRUD functionality for customer, booking, and trip records using MySQL.",
        "Investigated and fixed database connection, SQL query, and data validation issues.",
        "Used Git during development and worked in an Agile team."
      ],
      "concepts": [
        "Full-Stack Development",
        "Java",
        "MySQL",
        "CRUD",
        "HTTP",
        "JSON",
        "Database Integration",
        "Debugging",
        "Git",
        "Agile"
      ]
    },
    {
      "id": "proj-simulated-cinema-booking-system",
      "name": "Simulated Cinema Booking System",
      "institution": "Auckland University of Technology (AUT)",
      "year": 2021,
      "overview": "A console-based cinema booking application developed using Python and object-oriented programming.",
      "technology": [
        "Python",
        "Object-Oriented Programming"
      ],
      "development": [
        "Developed a console-based booking application using Python and object-oriented programming.",
        "Implemented movie browsing, seat selection, booking management, and payment calculation.",
        "Created reusable modules to separate application logic and improve maintainability.",
        "Debugged application logic and validated user input and booking workflows."
      ],
      "concepts": [
        "Python",
        "OOP",
        "Application Logic",
        "Reusable Modules",
        "Input Validation",
        "Debugging",
        "Maintainability"
      ]
    }
  ],
  "aiPractices": [
    {
      "id": "ai-ai-assisted-development",
      "name": "AI-Assisted Development",
      "description": "AI is part of Vincent's current development workflow. It should be presented as an engineering assistant, not as a replacement for engineering judgement.",
      "bullets": [],
      "tools": [
        "Claude",
        "GitHub Copilot"
      ],
      "usage": [
        "Generate initial JavaScript automation code.",
        "Debug JavaScript and automation issues.",
        "Improve existing automation code.",
        "Refactor duplicated automation logic.",
        "Generate and improve documentation.",
        "Support development of Playwright-based automation.",
        "Explore solutions to technical problems."
      ],
      "workflowSteps": []
    },
    {
      "id": "ai-ai-feature-testing",
      "name": "AI Feature Testing",
      "description": "Vincent has tested AI-powered application features and validated AI-generated results against expected business rules and application behaviour.\n\nRelevant experience includes:\n\n- Testing LLM-based chatbot behaviour.\n- Testing AI-powered invoice recognition.\n- Validating AI-generated results against business information and expected rules.\n- Investigating inconsistent AI outputs.\n- Considering application behaviour rather than relying only on exact text matching.",
      "bullets": [
        "Testing LLM-based chatbot behaviour.",
        "Testing AI-powered invoice recognition.",
        "Validating AI-generated results against business information and expected rules.",
        "Investigating inconsistent AI outputs.",
        "Considering application behaviour rather than relying only on exact text matching."
      ],
      "tools": [],
      "usage": [],
      "workflowSteps": []
    }
  ],
  "skills": [
    {
      "id": "skill-programming",
      "category": "Programming",
      "items": [
        "JavaScript",
        "Java",
        "Python",
        "SQL",
        "HTML",
        "CSS"
      ]
    },
    {
      "id": "skill-ai",
      "category": "AI",
      "items": [
        "Claude",
        "GitHub Copilot",
        "LLM / AI Feature Testing",
        "AI-Assisted Development"
      ]
    },
    {
      "id": "skill-web-and-apis",
      "category": "Web & APIs",
      "items": [
        "REST APIs",
        "JSON",
        "HTTP",
        "Postman",
        "Swagger"
      ]
    },
    {
      "id": "skill-test-automation",
      "category": "Test Automation",
      "items": [
        "Playwright",
        "Selenium",
        "Cucumber-JS",
        "Gherkin"
      ]
    },
    {
      "id": "skill-database",
      "category": "Database",
      "items": [
        "MySQL",
        "SQL",
        "Backend Data Validation",
        "Data Flow Investigation"
      ]
    },
    {
      "id": "skill-development-and-engineering-tools",
      "category": "Development & Engineering Tools",
      "items": [
        "Git",
        "Azure DevOps",
        "CI/CD",
        "Salesforce",
        "Mockoon"
      ]
    }
  ],
  "capabilities": [
    {
      "id": "cap-automation-engineering",
      "name": "Automation Engineering",
      "steps": [
        "JavaScript automation",
        "Playwright",
        "Page Object Model",
        "Reusable components",
        "Shared utilities",
        "BDD / Cucumber-JS",
        "End-to-end workflows"
      ]
    },
    {
      "id": "cap-api-and-integration",
      "name": "API & Integration",
      "steps": [
        "REST APIs",
        "HTTP",
        "JSON",
        "Postman",
        "Swagger",
        "Authentication validation",
        "Connected-system testing",
        "API and downstream-service investigation"
      ]
    },
    {
      "id": "cap-data-and-backend-validation",
      "name": "Data & Backend Validation",
      "steps": [
        "SQL",
        "MySQL",
        "Backend data validation",
        "Data-flow tracing",
        "Data consistency investigation"
      ]
    },
    {
      "id": "cap-ci-cd-and-engineering-workflow",
      "name": "CI/CD & Engineering Workflow",
      "steps": [
        "Azure DevOps",
        "CI/CD pipelines",
        "Pull request validation",
        "Scheduled test execution",
        "Release verification",
        "Git"
      ]
    },
    {
      "id": "cap-debugging-and-root-cause-investigation",
      "name": "Debugging & Root-Cause Investigation",
      "steps": [
        "Failure",
        "Logs, Trace, and API Response",
        "Reproduce",
        "Inspect Application Behaviour",
        "Check API and Data",
        "Identify Root Cause",
        "Verify Fix"
      ]
    },
    {
      "id": "cap-ai-assisted-engineering",
      "name": "AI-Assisted Engineering",
      "steps": [
        "Claude and GitHub Copilot",
        "Code Generation",
        "Human Review",
        "Debug and Refactor",
        "Requirement Validation",
        "Implementation"
      ]
    }
  ],
  "narrative": {
    "id": "narrative",
    "name": "Portfolio Narrative",
    "steps": []
  }
};
